service:
  name: tom-game-off-service
  publish: false

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'development'}
  region: ${opt:region, 'eu-west-1'}
  profile: ${opt:aws-profile, 'mable_dev'}
  timeout: 30 #default timeout for all handlers

package:
  individually: true

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-pseudo-parameters

functions:
  mqttUrl:
    handler: handlers/MqttUrl.run
    environment:
      SECRET: ${opt:secret, 'shhhh'}
      KEY: ${opt:key, 'keykey'}
    events:
      - http:
          path: game/connection
          method: get

